# Generated by Django 4.1.7 on 2023-05-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0007_booking_total_price_comment_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_station',
            field=models.BooleanField(default=False),
        ),
    ]
